run_test while_false_simple.test
run_test for_simple.test
run_test for_simple2.test
run_test for_simple3_letter.test
run_test for_do_ls.test
run_test for_do_ls_echo.test
run_test for_echo_quote.test
run_test for_echo_double_quote.test
run_test until_true.test
