run_test redir_simple.test
rm file
run_test redir2.test
rm file2
run_test redir3.test
rm file3
run_test redir4.test
rm file4
run_test redir5.test
run_test redir_stdout.test
run_test redir_stderr.test
