run_test echo_simple.test
run_test echo_double_pv.test
run_test echo_comment.test
run_test echo_newline.test
run_test echo_e.test
run_test echo_n.test
run_test echo_e_newline.test
run_test echo_E.test
run_test echo_ne.test
run_test echo_en.test
run_test echo_e_a_n.test
run_test echo_escape1.test
run_test echo_hard1.test
run_test echo_hard2.test
run_test echo_hard3.test
run_test echo_hard4.test
run_test list_echo_hard.test
run_test true.test
run_test false.test
run_test echo_e_fulltest.test
run_test echo_E_fulltest.test
run_test cd_tests.test
run_test cd_point_PWD.test
run_test cd_double_ls.test
run_test simple_export.test
run_test simple_export2.test
run_test export_PWD.test
run_test export_PWD2.test
run_test continue_simple.test
run_test break_simple.test
run_test continue_for.test
run_test break_for.test
run_test dot.test
run_test exit.test
run_test unset_v.test
run_test cd_moins.test
run_test double_continue.test
run_test double_break.test
run_test simple_unset.test
run_test simple_unset_v.test
run_test use_after_unset.test
run_test use_after_unset_v.test
run_test simple_unset_fonction.test
run_test use_unset_fonction.test
run_test use_unset_fonctioni_f.test
run_test unset_fonction_f.test
