run_test t_pipeline_f.test
run_test f_pipeline_t.test
run_test f_pipeline_f.test
run_test t_pipeline_t.test
run_test neg_t.test
run_test neg_f.test
run_test  if_neg_t.test
run_test  if_neg_f.test
run_test  elif_neg_f.test
run_test  elif_neg_t.test
run_test op_and_if_tt.test
run_test op_and_if_tf.test
run_test op_and_if_ft.test
run_test op_and_if_ff.test
run_test op_or_if_ff.test
run_test op_or_if_ft.test
run_test op_or_if_tf.test
run_test op_or_if_tt.test
run_test op_or_elif_tt.test
run_test op_or_elif_tf.test
run_test op_or_elif_ft.test
run_test op_or_elif_ff.test
run_test op_and_elif_ff.test
run_test op_and_elif_ft.test
run_test op_and_elif_tf.test
run_test op_and_elif_tt.test
run_test  op_echo_or.test
run_test  op_echo_and.test
run_test  echo_neg_f.test
run_test  echo_neg_t.test
run_test pipeline_is_if.test
run_test pipeline_is_if_echo.test
run_test pipeline_if_ft.test
