filetype on
syntax on
set background=dark
set linebreak
set visualbell
set showmatch
set hlsearch
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=2
set backspace=indent,eol,start
set mouse=a
set nufiletype on
syntax on
set background=dark
set linebreak
set visualbell
set showmatch
set hlsearch
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=2
set backspace=indent,eol,start
set mouse=a
set nu
